# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bloco.ui',
# licensing of 'bloco.ui' applies.
#
# Created: Fri Nov  1 14:36:53 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(499, 482)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icons/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setProperty("cursor", QtCore.Qt.IBeamCursor)
        self.textEdit.setAcceptDrops(True)
        self.textEdit.setAcceptRichText(True)
        self.textEdit.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.textEdit.setLineWrapColumnOrWidth(0)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.toolBar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.toolBar.setMovable(False)
        self.toolBar.setIconSize(QtCore.QSize(16, 16))
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_2.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.toolBar_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.toolBar_2.setMovable(False)
        self.toolBar_2.setIconSize(QtCore.QSize(20, 20))
        self.toolBar_2.setObjectName("toolBar_2")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        MainWindow.insertToolBarBreak(self.toolBar_2)
        self.actionAbrir = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/icons/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbrir.setIcon(icon1)
        self.actionAbrir.setObjectName("actionAbrir")
        self.actionSalvar = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSalvar.setIcon(icon2)
        self.actionSalvar.setObjectName("actionSalvar")
        self.actionNegrito = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/icons/bold-text-option.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNegrito.setIcon(icon3)
        self.actionNegrito.setObjectName("actionNegrito")
        self.actionItalico = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/icons/italicize-text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionItalico.setIcon(icon4)
        self.actionItalico.setObjectName("actionItalico")
        self.actionSublinhado = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/icons/underline-text-option.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSublinhado.setIcon(icon5)
        self.actionSublinhado.setObjectName("actionSublinhado")
        self.actionAlinhar_Esquerda = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/icons/align-to-left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAlinhar_Esquerda.setIcon(icon6)
        self.actionAlinhar_Esquerda.setObjectName("actionAlinhar_Esquerda")
        self.actionCentralizar = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/newPrefix/icons/center-text-alignment.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCentralizar.setIcon(icon7)
        self.actionCentralizar.setObjectName("actionCentralizar")
        self.actionAlinhar_Direita = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/newPrefix/icons/align-to-right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAlinhar_Direita.setIcon(icon8)
        self.actionAlinhar_Direita.setObjectName("actionAlinhar_Direita")
        self.actionNovo = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/newPrefix/icons/new-file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNovo.setIcon(icon9)
        self.actionNovo.setObjectName("actionNovo")
        self.actionCor_Fonte = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/newPrefix/icons/text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCor_Fonte.setIcon(icon10)
        self.actionCor_Fonte.setObjectName("actionCor_Fonte")
        self.actionLista = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/newPrefix/icons/list.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLista.setIcon(icon11)
        self.actionLista.setObjectName("actionLista")
        self.actionLista_Numerada = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/newPrefix/icons/numList.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLista_Numerada.setIcon(icon12)
        self.actionLista_Numerada.setObjectName("actionLista_Numerada")
        self.actionInserir_Imagem = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/newPrefix/icons/image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInserir_Imagem.setIcon(icon13)
        self.actionInserir_Imagem.setObjectName("actionInserir_Imagem")
        self.toolBar.addAction(self.actionNovo)
        self.toolBar.addAction(self.actionAbrir)
        self.toolBar.addAction(self.actionSalvar)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionNegrito)
        self.toolBar.addAction(self.actionItalico)
        self.toolBar.addAction(self.actionSublinhado)
        self.toolBar.addSeparator()
        self.toolBar_2.addAction(self.actionAlinhar_Esquerda)
        self.toolBar_2.addAction(self.actionCentralizar)
        self.toolBar_2.addAction(self.actionAlinhar_Direita)
        self.toolBar_2.addSeparator()
        self.toolBar_2.addAction(self.actionCor_Fonte)
        self.toolBar_2.addAction(self.actionLista)
        self.toolBar_2.addAction(self.actionLista_Numerada)
        self.toolBar_2.addAction(self.actionInserir_Imagem)
        
        #-----------------------------
        #ToolBar
        self.lbl = QtWidgets.QLabel(text=' Tamanho: ')
        self.toolBar.addWidget(self.lbl)
        self.spinBox = QtWidgets.QSpinBox()
        self.spinBox.setRange(8, 96)
        self.toolBar.addWidget(self.spinBox)
        self.lbl1 = QtWidgets.QLabel(text=' Fonte: ')
        self.toolBar.addWidget(self.lbl1)
        self.QfontComboBox = QtWidgets.QFontComboBox()
        self.QfontComboBox.setEditable(False)
        self.toolBar.addWidget(self.QfontComboBox)
        #----------------------------

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Bloco", None, -1))
        self.toolBar.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "toolBar", None, -1))
        self.toolBar_2.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "toolBar_2", None, -1))
        self.actionAbrir.setText(QtWidgets.QApplication.translate("MainWindow", "Abrir", None, -1))
        self.actionAbrir.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+O", None, -1))
        self.actionSalvar.setText(QtWidgets.QApplication.translate("MainWindow", "Salvar", None, -1))
        self.actionSalvar.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+S", None, -1))
        self.actionNegrito.setText(QtWidgets.QApplication.translate("MainWindow", "Negrito", None, -1))
        self.actionNegrito.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+B", None, -1))
        self.actionItalico.setText(QtWidgets.QApplication.translate("MainWindow", "Itálico", None, -1))
        self.actionItalico.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+I", None, -1))
        self.actionSublinhado.setText(QtWidgets.QApplication.translate("MainWindow", "Sublinhado", None, -1))
        self.actionSublinhado.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Shift+S", None, -1))
        self.actionAlinhar_Esquerda.setText(QtWidgets.QApplication.translate("MainWindow", "Alinhar a Esquerda", None, -1))
        self.actionCentralizar.setText(QtWidgets.QApplication.translate("MainWindow", "Centralizar", None, -1))
        self.actionAlinhar_Direita.setText(QtWidgets.QApplication.translate("MainWindow", "Alinhar a Direita", None, -1))
        self.actionNovo.setText(QtWidgets.QApplication.translate("MainWindow", "Novo", None, -1))
        self.actionCor_Fonte.setText(QtWidgets.QApplication.translate("MainWindow", "Cor da Fonte", None, -1))
        self.actionLista.setText(QtWidgets.QApplication.translate("MainWindow", "Lista", None, -1))
        self.actionLista_Numerada.setText(QtWidgets.QApplication.translate("MainWindow", "Lista Numerada", None, -1))
        self.actionInserir_Imagem.setText(QtWidgets.QApplication.translate("MainWindow", "Inserir Imagem", None, -1))

import recursos_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

